// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXNrX-zCcmCLU3RhLOASEsb5LkLMFtNs0',
    appId: '1:214017806001:web:7b4d08c40bf7b1c59fdc90',
    messagingSenderId: '214017806001',
    projectId: 'food-fleetdbs',
    authDomain: 'food-fleetdbs.firebaseapp.com',
    storageBucket: 'food-fleetdbs.firebasestorage.app',
    measurementId: 'G-FGCFKJ2HDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO-aF8pXCcN_lTLKtmRzaHoISTiQGSGRg',
    appId: '1:214017806001:android:dba06cbec67732c09fdc90',
    messagingSenderId: '214017806001',
    projectId: 'food-fleetdbs',
    storageBucket: 'food-fleetdbs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY1yq0VdmjVbR2HHjKl38AdkTQSthNjjk',
    appId: '1:214017806001:ios:7e01d2cfa8caa7c89fdc90',
    messagingSenderId: '214017806001',
    projectId: 'food-fleetdbs',
    storageBucket: 'food-fleetdbs.firebasestorage.app',
    iosBundleId: 'com.example.foodFleet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY1yq0VdmjVbR2HHjKl38AdkTQSthNjjk',
    appId: '1:214017806001:ios:7e01d2cfa8caa7c89fdc90',
    messagingSenderId: '214017806001',
    projectId: 'food-fleetdbs',
    storageBucket: 'food-fleetdbs.firebasestorage.app',
    iosBundleId: 'com.example.foodFleet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXNrX-zCcmCLU3RhLOASEsb5LkLMFtNs0',
    appId: '1:214017806001:web:8963b08f031895fc9fdc90',
    messagingSenderId: '214017806001',
    projectId: 'food-fleetdbs',
    authDomain: 'food-fleetdbs.firebaseapp.com',
    storageBucket: 'food-fleetdbs.firebasestorage.app',
    measurementId: 'G-YPX2VM70ZD',
  );
}
